spring:
  datasource:
    url: jdbc:mysql://localhost/todos?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: Macaco@10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true