spring:
  datasource:
    url: ${MYSQL_CONNECT_STRING:jdbc:mysql://localhost/todos?createDatabaseIfNotExist=true&serverTimezone=UTC}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:Macaco@10}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  loggly:
    token: ${LOGGLY_TOKEN}

security:
  jwt:
    expiration: 999999
    signKey: ${JWT_SIGN_KEY:31d6cfe0d16ae931b73c59d7e0c089c0}